/**
 * AUTO-GENERATED by scripts/build-model-photos.js — do not hand-edit.
 * Regenerate with: node scripts/build-model-photos.js
 */
export interface ModelPhoto { name: string; image: string; }
export interface ModelSeries { name: string; models: ModelPhoto[]; }

export const modelPhotoCatalog: Record<string, ModelSeries[]> = {
  "apple": [
    {
      "name": "iPhone",
      "models": [
        {
          "name": "iPhone 17 Pro Max",
          "image": "/images/models/apple/iphone-17-pro-max.webp"
        },
        {
          "name": "iPhone 17 Pro",
          "image": "/images/models/apple/iphone-17-pro.webp"
        },
        {
          "name": "iPhone 17",
          "image": "/images/models/apple/iphone-17.webp"
        },
        {
          "name": "iPhone 17 Air",
          "image": "/images/models/apple/iphone-17-air.webp"
        },
        {
          "name": "iPhone 17e",
          "image": "/images/models/apple/iphone-17e.webp"
        },
        {
          "name": "iPhone 16 Pro Max",
          "image": "/images/models/apple/iphone-16-pro-max.webp"
        },
        {
          "name": "iPhone 16 Pro",
          "image": "/images/models/apple/iphone-16-pro.webp"
        },
        {
          "name": "iPhone 16 Plus",
          "image": "/images/models/apple/iphone-16-plus.webp"
        },
        {
          "name": "iPhone 16",
          "image": "/images/models/apple/iphone-16.webp"
        },
        {
          "name": "iPhone 16e",
          "image": "/images/models/apple/iphone-16e.webp"
        },
        {
          "name": "iPhone 15 Pro Max",
          "image": "/images/models/apple/iphone-15-pro-max.webp"
        },
        {
          "name": "iPhone 15 Plus",
          "image": "/images/models/apple/iphone-15-plus.webp"
        },
        {
          "name": "iPhone 15",
          "image": "/images/models/apple/iphone-15.webp"
        },
        {
          "name": "iPhone 14 Pro Max",
          "image": "/images/models/apple/iphone-14-pro-max.webp"
        },
        {
          "name": "iPhone 14 Pro",
          "image": "/images/models/apple/iphone-14-pro.webp"
        },
        {
          "name": "iPhone 14 Plus",
          "image": "/images/models/apple/iphone-14-plus.webp"
        },
        {
          "name": "iPhone 14",
          "image": "/images/models/apple/iphone-14.webp"
        },
        {
          "name": "iPhone 13 Pro Max",
          "image": "/images/models/apple/iphone-13-pro-max.webp"
        },
        {
          "name": "iPhone 13 Pro",
          "image": "/images/models/apple/iphone-13-pro.webp"
        },
        {
          "name": "iPhone 13",
          "image": "/images/models/apple/iphone-13.webp"
        },
        {
          "name": "iPhone 13 Mini",
          "image": "/images/models/apple/iphone-13-mini.webp"
        },
        {
          "name": "iPhone 12 Pro Max",
          "image": "/images/models/apple/iphone-12-pro-max.webp"
        },
        {
          "name": "iPhone 12 Pro",
          "image": "/images/models/apple/iphone-12-pro.webp"
        },
        {
          "name": "iPhone 12",
          "image": "/images/models/apple/iphone-12.webp"
        },
        {
          "name": "iPhone 12 Mini",
          "image": "/images/models/apple/iphone-12-mini.webp"
        },
        {
          "name": "iPhone SE (2020)",
          "image": "/images/models/apple/iphone-se-2020.webp"
        },
        {
          "name": "iPhone 11 Pro Max",
          "image": "/images/models/apple/iphone-11-pro-max.webp"
        },
        {
          "name": "iPhone 11 Pro",
          "image": "/images/models/apple/iphone-11-pro.webp"
        },
        {
          "name": "iPhone 11",
          "image": "/images/models/apple/iphone-11.webp"
        },
        {
          "name": "iPhone XS Max",
          "image": "/images/models/apple/iphone-xs-max.webp"
        },
        {
          "name": "iPhone XS",
          "image": "/images/models/apple/iphone-xs.webp"
        },
        {
          "name": "iPhone XR",
          "image": "/images/models/apple/iphone-xr.webp"
        },
        {
          "name": "iPhone X",
          "image": "/images/models/apple/iphone-x.webp"
        },
        {
          "name": "iPhone 8 Plus",
          "image": "/images/models/apple/iphone-8-plus.webp"
        },
        {
          "name": "iPhone 8",
          "image": "/images/models/apple/iphone-8.webp"
        },
        {
          "name": "iPhone 7 Plus",
          "image": "/images/models/apple/iphone-7-plus.webp"
        },
        {
          "name": "iPhone 7",
          "image": "/images/models/apple/iphone-7.webp"
        },
        {
          "name": "iPhone SE (2016)",
          "image": "/images/models/apple/iphone-se-2016.webp"
        },
        {
          "name": "iPhone 6 Plus",
          "image": "/images/models/apple/iphone-6-plus.webp"
        },
        {
          "name": "iPhone 6s",
          "image": "/images/models/apple/iphone-6s.webp"
        },
        {
          "name": "iPhone 6",
          "image": "/images/models/apple/iphone-6.webp"
        }
      ]
    },
    {
      "name": "Other",
      "models": [
        {
          "name": "Other iPhone Model",
          "image": "/images/models/apple/other.webp"
        }
      ]
    }
  ],
  "samsung": [
    {
      "name": "Galaxy S",
      "models": [
        {
          "name": "Galaxy S25 Ultra",
          "image": "/images/models/samsung/galaxy-s25-ultra.webp"
        },
        {
          "name": "Galaxy S25+",
          "image": "/images/models/samsung/galaxy-s25-plus.webp"
        },
        {
          "name": "Galaxy S25",
          "image": "/images/models/samsung/galaxy-s25.webp"
        },
        {
          "name": "Galaxy S25 FE",
          "image": "/images/models/samsung/galaxy-s25-fe.webp"
        },
        {
          "name": "Galaxy S24 Ultra",
          "image": "/images/models/samsung/galaxy-s24-ultra.webp"
        },
        {
          "name": "Galaxy S24+",
          "image": "/images/models/samsung/galaxy-s24-plus.webp"
        },
        {
          "name": "Galaxy S24",
          "image": "/images/models/samsung/galaxy-s24.webp"
        },
        {
          "name": "Galaxy S24 FE",
          "image": "/images/models/samsung/galaxy-s24-fe.webp"
        },
        {
          "name": "Galaxy S23 Ultra",
          "image": "/images/models/samsung/galaxy-s23-ultra.webp"
        },
        {
          "name": "Galaxy S23+",
          "image": "/images/models/samsung/galaxy-s23-plus.webp"
        },
        {
          "name": "Galaxy S23",
          "image": "/images/models/samsung/galaxy-s23.webp"
        },
        {
          "name": "Galaxy S23 FE",
          "image": "/images/models/samsung/galaxy-s23-fe.webp"
        },
        {
          "name": "Galaxy S22 Ultra",
          "image": "/images/models/samsung/galaxy-s22-ultra.webp"
        },
        {
          "name": "Galaxy S22+",
          "image": "/images/models/samsung/galaxy-s22-plus.webp"
        },
        {
          "name": "Galaxy S22",
          "image": "/images/models/samsung/galaxy-s22.webp"
        },
        {
          "name": "Galaxy S21 Ultra",
          "image": "/images/models/samsung/galaxy-s21-ultra.webp"
        },
        {
          "name": "Galaxy S21+",
          "image": "/images/models/samsung/galaxy-s21-plus.webp"
        },
        {
          "name": "Galaxy S21",
          "image": "/images/models/samsung/galaxy-s21.webp"
        },
        {
          "name": "Galaxy S21 FE",
          "image": "/images/models/samsung/galaxy-s21-fe.webp"
        },
        {
          "name": "Galaxy S20 Ultra",
          "image": "/images/models/samsung/galaxy-s20-ultra.webp"
        },
        {
          "name": "Galaxy S20+",
          "image": "/images/models/samsung/galaxy-s20-plus.webp"
        },
        {
          "name": "Galaxy S20",
          "image": "/images/models/samsung/galaxy-s20.webp"
        },
        {
          "name": "Galaxy S20 FE",
          "image": "/images/models/samsung/galaxy-s20-fe.webp"
        },
        {
          "name": "Galaxy S10+",
          "image": "/images/models/samsung/galaxy-s10-plus.webp"
        },
        {
          "name": "Galaxy S10",
          "image": "/images/models/samsung/galaxy-s10.webp"
        },
        {
          "name": "Galaxy S10e",
          "image": "/images/models/samsung/galaxy-s10e.webp"
        },
        {
          "name": "Galaxy S10 Lite",
          "image": "/images/models/samsung/galaxy-s10-lite.webp"
        },
        {
          "name": "Galaxy S9+",
          "image": "/images/models/samsung/galaxy-s9-plus.webp"
        },
        {
          "name": "Galaxy S9",
          "image": "/images/models/samsung/galaxy-s9.webp"
        },
        {
          "name": "Galaxy S8+",
          "image": "/images/models/samsung/galaxy-s8-plus.webp"
        },
        {
          "name": "Galaxy S8",
          "image": "/images/models/samsung/galaxy-s8.webp"
        },
        {
          "name": "Galaxy S7 Edge",
          "image": "/images/models/samsung/galaxy-s7-edge.webp"
        }
      ]
    },
    {
      "name": "Galaxy Z",
      "models": [
        {
          "name": "Galaxy Z Fold 7",
          "image": "/images/models/samsung/galaxy-z-fold-7.webp"
        },
        {
          "name": "Galaxy Z Fold 6",
          "image": "/images/models/samsung/galaxy-z-fold-6.webp"
        },
        {
          "name": "Galaxy Z Fold 5",
          "image": "/images/models/samsung/galaxy-z-fold-5.webp"
        },
        {
          "name": "Galaxy Z Fold 4",
          "image": "/images/models/samsung/galaxy-z-fold-4.webp"
        },
        {
          "name": "Galaxy Z Fold 3",
          "image": "/images/models/samsung/galaxy-z-fold-3.webp"
        },
        {
          "name": "Galaxy Z Fold 2",
          "image": "/images/models/samsung/galaxy-z-fold-2.webp"
        },
        {
          "name": "Galaxy Z Flip 7",
          "image": "/images/models/samsung/galaxy-z-flip-7.webp"
        },
        {
          "name": "Galaxy Z Flip 6",
          "image": "/images/models/samsung/galaxy-z-flip-6.webp"
        },
        {
          "name": "Galaxy Z Flip 5",
          "image": "/images/models/samsung/galaxy-z-flip-5.webp"
        },
        {
          "name": "Galaxy Z Flip 4",
          "image": "/images/models/samsung/galaxy-z-flip-4.webp"
        },
        {
          "name": "Galaxy Z Flip 3",
          "image": "/images/models/samsung/galaxy-z-flip-3.webp"
        }
      ]
    },
    {
      "name": "Galaxy Note",
      "models": [
        {
          "name": "Galaxy Note 20 Ultra",
          "image": "/images/models/samsung/galaxy-note-20-ultra.webp"
        },
        {
          "name": "Galaxy Note 20",
          "image": "/images/models/samsung/galaxy-note-20.webp"
        },
        {
          "name": "Galaxy Note 10+",
          "image": "/images/models/samsung/galaxy-note-10-plus.webp"
        },
        {
          "name": "Galaxy Note 10",
          "image": "/images/models/samsung/galaxy-note-10.webp"
        },
        {
          "name": "Galaxy Note 10 Lite",
          "image": "/images/models/samsung/galaxy-note-10-lite.webp"
        },
        {
          "name": "Galaxy Note 9",
          "image": "/images/models/samsung/galaxy-note-9.webp"
        },
        {
          "name": "Galaxy Note 8",
          "image": "/images/models/samsung/galaxy-note-8.webp"
        }
      ]
    },
    {
      "name": "Galaxy A",
      "models": [
        {
          "name": "Galaxy A56",
          "image": "/images/models/samsung/galaxy-a56.webp"
        },
        {
          "name": "Galaxy A55",
          "image": "/images/models/samsung/galaxy-a55.webp"
        },
        {
          "name": "Galaxy A54",
          "image": "/images/models/samsung/galaxy-a54.webp"
        },
        {
          "name": "Galaxy A53",
          "image": "/images/models/samsung/galaxy-a53.webp"
        },
        {
          "name": "Galaxy A52s",
          "image": "/images/models/samsung/galaxy-a52s.webp"
        },
        {
          "name": "Galaxy A52 5G",
          "image": "/images/models/samsung/galaxy-a52-5g.webp"
        },
        {
          "name": "Galaxy A52",
          "image": "/images/models/samsung/galaxy-a52.webp"
        },
        {
          "name": "Galaxy A51 5G",
          "image": "/images/models/samsung/galaxy-a51-5g.webp"
        },
        {
          "name": "Galaxy A51",
          "image": "/images/models/samsung/galaxy-a51.webp"
        },
        {
          "name": "Galaxy A50s",
          "image": "/images/models/samsung/galaxy-a50s.webp"
        },
        {
          "name": "Galaxy A50",
          "image": "/images/models/samsung/galaxy-a50.webp"
        },
        {
          "name": "Galaxy A42 5G",
          "image": "/images/models/samsung/galaxy-a42-5g.webp"
        },
        {
          "name": "Galaxy A41",
          "image": "/images/models/samsung/galaxy-a41.webp"
        },
        {
          "name": "Galaxy A36",
          "image": "/images/models/samsung/galaxy-a36.webp"
        },
        {
          "name": "Galaxy A35",
          "image": "/images/models/samsung/galaxy-a35.webp"
        },
        {
          "name": "Galaxy A34",
          "image": "/images/models/samsung/galaxy-a34.webp"
        },
        {
          "name": "Galaxy A33",
          "image": "/images/models/samsung/galaxy-a33.webp"
        },
        {
          "name": "Galaxy A32 5G",
          "image": "/images/models/samsung/galaxy-a32-5g.webp"
        },
        {
          "name": "Galaxy A32",
          "image": "/images/models/samsung/galaxy-a32.webp"
        },
        {
          "name": "Galaxy A31",
          "image": "/images/models/samsung/galaxy-a31.webp"
        },
        {
          "name": "Galaxy A30s",
          "image": "/images/models/samsung/galaxy-a30s.webp"
        },
        {
          "name": "Galaxy A30",
          "image": "/images/models/samsung/galaxy-a30.webp"
        },
        {
          "name": "Galaxy A23 5G",
          "image": "/images/models/samsung/galaxy-a23-5g.webp"
        },
        {
          "name": "Galaxy A23",
          "image": "/images/models/samsung/galaxy-a23.webp"
        },
        {
          "name": "Galaxy A22 5G",
          "image": "/images/models/samsung/galaxy-a22-5g.webp"
        },
        {
          "name": "Galaxy A22",
          "image": "/images/models/samsung/galaxy-a22.webp"
        },
        {
          "name": "Galaxy A21s",
          "image": "/images/models/samsung/galaxy-a21s.webp"
        },
        {
          "name": "Galaxy A21",
          "image": "/images/models/samsung/galaxy-a21.webp"
        },
        {
          "name": "Galaxy A20s",
          "image": "/images/models/samsung/galaxy-a20s.webp"
        },
        {
          "name": "Galaxy A16",
          "image": "/images/models/samsung/galaxy-a16.webp"
        },
        {
          "name": "Galaxy A15",
          "image": "/images/models/samsung/galaxy-a15.webp"
        },
        {
          "name": "Galaxy A14 5G",
          "image": "/images/models/samsung/galaxy-a14-5g.webp"
        },
        {
          "name": "Galaxy A14",
          "image": "/images/models/samsung/galaxy-a14.webp"
        },
        {
          "name": "Galaxy A13 5G",
          "image": "/images/models/samsung/galaxy-a13-5g.webp"
        },
        {
          "name": "Galaxy A13",
          "image": "/images/models/samsung/galaxy-a13.webp"
        },
        {
          "name": "Galaxy A12",
          "image": "/images/models/samsung/galaxy-a12.webp"
        },
        {
          "name": "Galaxy A11",
          "image": "/images/models/samsung/galaxy-a11.webp"
        },
        {
          "name": "Galaxy A10s",
          "image": "/images/models/samsung/galaxy-a10s.webp"
        },
        {
          "name": "Galaxy A10",
          "image": "/images/models/samsung/galaxy-a10.webp"
        },
        {
          "name": "Galaxy A90 5G",
          "image": "/images/models/samsung/galaxy-a90-5g.webp"
        },
        {
          "name": "Galaxy A80",
          "image": "/images/models/samsung/galaxy-a80.webp"
        },
        {
          "name": "Galaxy A73 5G",
          "image": "/images/models/samsung/galaxy-a73-5g.webp"
        },
        {
          "name": "Galaxy A72",
          "image": "/images/models/samsung/galaxy-a72.webp"
        },
        {
          "name": "Galaxy A71 5G",
          "image": "/images/models/samsung/galaxy-a71-5g.webp"
        },
        {
          "name": "Galaxy A71",
          "image": "/images/models/samsung/galaxy-a71.webp"
        },
        {
          "name": "Galaxy A70s",
          "image": "/images/models/samsung/galaxy-a70s.webp"
        },
        {
          "name": "Galaxy A70",
          "image": "/images/models/samsung/galaxy-a70.webp"
        },
        {
          "name": "Galaxy A60",
          "image": "/images/models/samsung/galaxy-a60.webp"
        },
        {
          "name": "Galaxy A06",
          "image": "/images/models/samsung/galaxy-a06.webp"
        },
        {
          "name": "Galaxy A05",
          "image": "/images/models/samsung/galaxy-a05.webp"
        },
        {
          "name": "Galaxy A04",
          "image": "/images/models/samsung/galaxy-a04.webp"
        },
        {
          "name": "Galaxy A03s",
          "image": "/images/models/samsung/galaxy-a03s.webp"
        },
        {
          "name": "Galaxy A03",
          "image": "/images/models/samsung/galaxy-a03.webp"
        },
        {
          "name": "Galaxy A03 Core",
          "image": "/images/models/samsung/galaxy-a03-core.webp"
        },
        {
          "name": "Galaxy A02s",
          "image": "/images/models/samsung/galaxy-a02s.webp"
        },
        {
          "name": "Galaxy A02",
          "image": "/images/models/samsung/galaxy-a02.webp"
        },
        {
          "name": "Galaxy A01 Core",
          "image": "/images/models/samsung/galaxy-a01-core.webp"
        },
        {
          "name": "Galaxy A01",
          "image": "/images/models/samsung/galaxy-a01.webp"
        }
      ]
    },
    {
      "name": "Galaxy M",
      "models": [
        {
          "name": "Galaxy M56",
          "image": "/images/models/samsung/galaxy-m56.webp"
        },
        {
          "name": "Galaxy M55",
          "image": "/images/models/samsung/galaxy-m55.webp"
        },
        {
          "name": "Galaxy M54",
          "image": "/images/models/samsung/galaxy-m54.webp"
        },
        {
          "name": "Galaxy M53",
          "image": "/images/models/samsung/galaxy-m53.webp"
        },
        {
          "name": "Galaxy M52",
          "image": "/images/models/samsung/galaxy-m52.webp"
        },
        {
          "name": "Galaxy M51",
          "image": "/images/models/samsung/galaxy-m51.webp"
        },
        {
          "name": "Galaxy M42 5G",
          "image": "/images/models/samsung/galaxy-m42-5g.webp"
        },
        {
          "name": "Galaxy M40",
          "image": "/images/models/samsung/galaxy-m40.webp"
        },
        {
          "name": "Galaxy M36",
          "image": "/images/models/samsung/galaxy-m36.webp"
        },
        {
          "name": "Galaxy M35",
          "image": "/images/models/samsung/galaxy-m35.webp"
        },
        {
          "name": "Galaxy M34",
          "image": "/images/models/samsung/galaxy-m34.webp"
        },
        {
          "name": "Galaxy M33",
          "image": "/images/models/samsung/galaxy-m33.webp"
        },
        {
          "name": "Galaxy M32 5G",
          "image": "/images/models/samsung/galaxy-m32-5g.webp"
        },
        {
          "name": "Galaxy M32",
          "image": "/images/models/samsung/galaxy-m32.webp"
        },
        {
          "name": "Galaxy M31 Prime",
          "image": "/images/models/samsung/galaxy-m31-prime.webp"
        },
        {
          "name": "Galaxy M31s",
          "image": "/images/models/samsung/galaxy-m31s.webp"
        },
        {
          "name": "Galaxy M31",
          "image": "/images/models/samsung/galaxy-m31.webp"
        },
        {
          "name": "Galaxy M30",
          "image": "/images/models/samsung/galaxy-m30.webp"
        },
        {
          "name": "Galaxy M21",
          "image": "/images/models/samsung/galaxy-m21.webp"
        },
        {
          "name": "Galaxy M20",
          "image": "/images/models/samsung/galaxy-m20.webp"
        },
        {
          "name": "Galaxy M16",
          "image": "/images/models/samsung/galaxy-m16.webp"
        },
        {
          "name": "Galaxy M15",
          "image": "/images/models/samsung/galaxy-m15.webp"
        },
        {
          "name": "Galaxy M14",
          "image": "/images/models/samsung/galaxy-m14.webp"
        },
        {
          "name": "Galaxy M13",
          "image": "/images/models/samsung/galaxy-m13.webp"
        },
        {
          "name": "Galaxy M12",
          "image": "/images/models/samsung/galaxy-m12.webp"
        },
        {
          "name": "Galaxy M11",
          "image": "/images/models/samsung/galaxy-m11.webp"
        },
        {
          "name": "Galaxy M10s",
          "image": "/images/models/samsung/galaxy-m10s.webp"
        },
        {
          "name": "Galaxy M10",
          "image": "/images/models/samsung/galaxy-m10.webp"
        },
        {
          "name": "Galaxy M06",
          "image": "/images/models/samsung/galaxy-m06.webp"
        },
        {
          "name": "Galaxy M04",
          "image": "/images/models/samsung/galaxy-m04.webp"
        },
        {
          "name": "Galaxy M02s",
          "image": "/images/models/samsung/galaxy-m02s.webp"
        },
        {
          "name": "Galaxy M02",
          "image": "/images/models/samsung/galaxy-m02.webp"
        },
        {
          "name": "Galaxy M01 Core",
          "image": "/images/models/samsung/galaxy-m01-core.webp"
        },
        {
          "name": "Galaxy M01s",
          "image": "/images/models/samsung/galaxy-m01s.webp"
        },
        {
          "name": "Galaxy M01",
          "image": "/images/models/samsung/galaxy-m01.webp"
        }
      ]
    },
    {
      "name": "Galaxy F",
      "models": [
        {
          "name": "Galaxy F62",
          "image": "/images/models/samsung/galaxy-f62.webp"
        },
        {
          "name": "Galaxy F54",
          "image": "/images/models/samsung/galaxy-f54.webp"
        },
        {
          "name": "Galaxy F42 5G",
          "image": "/images/models/samsung/galaxy-f42-5g.webp"
        },
        {
          "name": "Galaxy F41",
          "image": "/images/models/samsung/galaxy-f41.webp"
        },
        {
          "name": "Galaxy F34",
          "image": "/images/models/samsung/galaxy-f34.webp"
        },
        {
          "name": "Galaxy F23",
          "image": "/images/models/samsung/galaxy-f23.webp"
        },
        {
          "name": "Galaxy F22",
          "image": "/images/models/samsung/galaxy-f22.webp"
        },
        {
          "name": "Galaxy F12",
          "image": "/images/models/samsung/galaxy-f12.webp"
        },
        {
          "name": "Galaxy F04",
          "image": "/images/models/samsung/galaxy-f04.webp"
        },
        {
          "name": "Galaxy F02s",
          "image": "/images/models/samsung/galaxy-f02s.webp"
        }
      ]
    },
    {
      "name": "Galaxy J",
      "models": [
        {
          "name": "Galaxy J8",
          "image": "/images/models/samsung/galaxy-j8.webp"
        },
        {
          "name": "Galaxy J7 Pro",
          "image": "/images/models/samsung/galaxy-j7-pro.webp"
        },
        {
          "name": "Galaxy J7 Prime",
          "image": "/images/models/samsung/galaxy-j7-prime.webp"
        },
        {
          "name": "Galaxy J7 Max",
          "image": "/images/models/samsung/galaxy-j7-max.webp"
        },
        {
          "name": "Galaxy J7 Duo",
          "image": "/images/models/samsung/galaxy-j7-duo.webp"
        },
        {
          "name": "Galaxy J7 Nxt",
          "image": "/images/models/samsung/galaxy-j7-nxt.webp"
        },
        {
          "name": "Galaxy J7",
          "image": "/images/models/samsung/galaxy-j7.webp"
        },
        {
          "name": "Galaxy J6+",
          "image": "/images/models/samsung/galaxy-j6-plus.webp"
        },
        {
          "name": "Galaxy J6",
          "image": "/images/models/samsung/galaxy-j6.webp"
        }
      ]
    },
    {
      "name": "Other",
      "models": [
        {
          "name": "Other Samsung Model",
          "image": "/images/models/samsung/other.webp"
        }
      ]
    }
  ],
  "google-pixel": [
    {
      "name": "Pixel",
      "models": [
        {
          "name": "Pixel 11 Pro Fold",
          "image": "/images/models/google-pixel/pixel-11-pro-fold.webp"
        },
        {
          "name": "Pixel 11 Pro XL",
          "image": "/images/models/google-pixel/pixel-11-pro-xl.webp"
        },
        {
          "name": "Pixel 11 Pro",
          "image": "/images/models/google-pixel/pixel-11-pro.webp"
        },
        {
          "name": "Pixel 11",
          "image": "/images/models/google-pixel/pixel-11.webp"
        },
        {
          "name": "Pixel 10 Pro Fold",
          "image": "/images/models/google-pixel/pixel-10-pro-fold.webp"
        },
        {
          "name": "Pixel 10 Pro XL",
          "image": "/images/models/google-pixel/pixel-10-pro-xl.webp"
        },
        {
          "name": "Pixel 10 Pro",
          "image": "/images/models/google-pixel/pixel-10-pro.webp"
        },
        {
          "name": "Pixel 10",
          "image": "/images/models/google-pixel/pixel-10.webp"
        },
        {
          "name": "Pixel 10a",
          "image": "/images/models/google-pixel/pixel-10a.webp"
        },
        {
          "name": "Pixel 9 Pro Fold",
          "image": "/images/models/google-pixel/pixel-9-pro-fold.webp"
        },
        {
          "name": "Pixel 9 Pro XL",
          "image": "/images/models/google-pixel/pixel-9-pro-xl.webp"
        },
        {
          "name": "Pixel 9 Pro",
          "image": "/images/models/google-pixel/pixel-9-pro.webp"
        },
        {
          "name": "Pixel 9",
          "image": "/images/models/google-pixel/pixel-9.webp"
        },
        {
          "name": "Pixel 9a",
          "image": "/images/models/google-pixel/pixel-9a.webp"
        },
        {
          "name": "Pixel Fold",
          "image": "/images/models/google-pixel/pixel-fold.webp"
        },
        {
          "name": "Pixel 8 Pro",
          "image": "/images/models/google-pixel/pixel-8-pro.webp"
        },
        {
          "name": "Pixel 8",
          "image": "/images/models/google-pixel/pixel-8.webp"
        },
        {
          "name": "Pixel 8a",
          "image": "/images/models/google-pixel/pixel-8a.webp"
        },
        {
          "name": "Pixel 7 Pro",
          "image": "/images/models/google-pixel/pixel-7-pro.webp"
        },
        {
          "name": "Pixel 7",
          "image": "/images/models/google-pixel/pixel-7.webp"
        },
        {
          "name": "Pixel 7a",
          "image": "/images/models/google-pixel/pixel-7a.webp"
        },
        {
          "name": "Pixel 6 Pro",
          "image": "/images/models/google-pixel/pixel-6-pro.webp"
        },
        {
          "name": "Pixel 6",
          "image": "/images/models/google-pixel/pixel-6.webp"
        },
        {
          "name": "Pixel 6a",
          "image": "/images/models/google-pixel/pixel-6a.webp"
        },
        {
          "name": "Pixel 5",
          "image": "/images/models/google-pixel/pixel-5.webp"
        },
        {
          "name": "Pixel 5a",
          "image": "/images/models/google-pixel/pixel-5a.webp"
        },
        {
          "name": "Pixel 4",
          "image": "/images/models/google-pixel/pixel-4.webp"
        },
        {
          "name": "Pixel 4a 5G",
          "image": "/images/models/google-pixel/pixel-4a-5g.webp"
        },
        {
          "name": "Pixel 3 XL",
          "image": "/images/models/google-pixel/pixel-3-xl.webp"
        },
        {
          "name": "Pixel 3a XL",
          "image": "/images/models/google-pixel/pixel-3a-xl.webp"
        },
        {
          "name": "Pixel 3a",
          "image": "/images/models/google-pixel/pixel-3a.webp"
        },
        {
          "name": "Pixel XL",
          "image": "/images/models/google-pixel/pixel-xl.webp"
        },
        {
          "name": "Pixel 2 XL",
          "image": "/images/models/google-pixel/pixel-2-xl.webp"
        },
        {
          "name": "Pixel 2",
          "image": "/images/models/google-pixel/pixel-2.webp"
        }
      ]
    }
  ],
  "oneplus": [
    {
      "name": "OnePlus",
      "models": [
        {
          "name": "OnePlus 15",
          "image": "/images/models/oneplus/oneplus-15.webp"
        },
        {
          "name": "OnePlus 15R",
          "image": "/images/models/oneplus/oneplus-15r.webp"
        },
        {
          "name": "OnePlus 13s",
          "image": "/images/models/oneplus/oneplus-13s.webp"
        },
        {
          "name": "OnePlus 13",
          "image": "/images/models/oneplus/oneplus-13.webp"
        },
        {
          "name": "OnePlus 13R",
          "image": "/images/models/oneplus/oneplus-13r.webp"
        },
        {
          "name": "OnePlus 12",
          "image": "/images/models/oneplus/oneplus-12.webp"
        },
        {
          "name": "OnePlus 12R",
          "image": "/images/models/oneplus/oneplus-12r.webp"
        },
        {
          "name": "OnePlus Open",
          "image": "/images/models/oneplus/oneplus-open.webp"
        },
        {
          "name": "OnePlus 11",
          "image": "/images/models/oneplus/oneplus-11.webp"
        },
        {
          "name": "OnePlus 11R",
          "image": "/images/models/oneplus/oneplus-11r.webp"
        },
        {
          "name": "OnePlus 10 Pro",
          "image": "/images/models/oneplus/oneplus-10-pro.webp"
        },
        {
          "name": "OnePlus 10T",
          "image": "/images/models/oneplus/oneplus-10t.webp"
        },
        {
          "name": "OnePlus 10R",
          "image": "/images/models/oneplus/oneplus-10r.webp"
        },
        {
          "name": "OnePlus 9 Pro",
          "image": "/images/models/oneplus/oneplus-9-pro.webp"
        },
        {
          "name": "OnePlus 9",
          "image": "/images/models/oneplus/oneplus-9.webp"
        },
        {
          "name": "OnePlus 9RT",
          "image": "/images/models/oneplus/oneplus-9rt.webp"
        },
        {
          "name": "OnePlus 9R",
          "image": "/images/models/oneplus/oneplus-9r.webp"
        },
        {
          "name": "OnePlus 8 Pro",
          "image": "/images/models/oneplus/oneplus-8-pro.webp"
        },
        {
          "name": "OnePlus 8T",
          "image": "/images/models/oneplus/oneplus-8t.webp"
        },
        {
          "name": "OnePlus 8",
          "image": "/images/models/oneplus/oneplus-8.webp"
        },
        {
          "name": "OnePlus 7 Pro",
          "image": "/images/models/oneplus/oneplus-7-pro.webp"
        },
        {
          "name": "OnePlus 7T Pro",
          "image": "/images/models/oneplus/oneplus-7t-pro.webp"
        },
        {
          "name": "OnePlus 7T",
          "image": "/images/models/oneplus/oneplus-7t.webp"
        },
        {
          "name": "OnePlus 7",
          "image": "/images/models/oneplus/oneplus-7.webp"
        },
        {
          "name": "OnePlus 6T",
          "image": "/images/models/oneplus/oneplus-6t.webp"
        },
        {
          "name": "OnePlus 6",
          "image": "/images/models/oneplus/oneplus-6.webp"
        },
        {
          "name": "OnePlus 5T",
          "image": "/images/models/oneplus/oneplus-5t.webp"
        },
        {
          "name": "OnePlus 5",
          "image": "/images/models/oneplus/oneplus-5.webp"
        },
        {
          "name": "OnePlus 3T",
          "image": "/images/models/oneplus/oneplus-3t.webp"
        },
        {
          "name": "OnePlus 3",
          "image": "/images/models/oneplus/oneplus-3.webp"
        }
      ]
    },
    {
      "name": "OnePlus Nord",
      "models": [
        {
          "name": "OnePlus Nord 5",
          "image": "/images/models/oneplus/oneplus-nord-5.webp"
        },
        {
          "name": "OnePlus Nord CE 5",
          "image": "/images/models/oneplus/oneplus-nord-ce-5.webp"
        },
        {
          "name": "OnePlus Nord 4",
          "image": "/images/models/oneplus/oneplus-nord-4.webp"
        },
        {
          "name": "OnePlus Nord CE 4",
          "image": "/images/models/oneplus/oneplus-nord-ce-4.webp"
        },
        {
          "name": "OnePlus Nord CE 4 Lite",
          "image": "/images/models/oneplus/oneplus-nord-ce-4-lite.webp"
        },
        {
          "name": "OnePlus Nord 3",
          "image": "/images/models/oneplus/oneplus-nord-3.webp"
        },
        {
          "name": "OnePlus Nord CE 3",
          "image": "/images/models/oneplus/oneplus-nord-ce-3.webp"
        },
        {
          "name": "OnePlus Nord CE 3 Lite",
          "image": "/images/models/oneplus/oneplus-nord-ce-3-lite.webp"
        },
        {
          "name": "OnePlus Nord 2T",
          "image": "/images/models/oneplus/oneplus-nord-2t.webp"
        },
        {
          "name": "OnePlus Nord 2",
          "image": "/images/models/oneplus/oneplus-nord-2.webp"
        },
        {
          "name": "OnePlus Nord CE 2",
          "image": "/images/models/oneplus/oneplus-nord-ce-2.webp"
        },
        {
          "name": "OnePlus Nord CE 2 Lite",
          "image": "/images/models/oneplus/oneplus-nord-ce-2-lite.webp"
        },
        {
          "name": "OnePlus Nord CE",
          "image": "/images/models/oneplus/oneplus-nord-ce.webp"
        },
        {
          "name": "OnePlus Nord",
          "image": "/images/models/oneplus/oneplus-nord.webp"
        }
      ]
    },
    {
      "name": "Other",
      "models": [
        {
          "name": "Other OnePlus Model",
          "image": "/images/models/oneplus/other.webp"
        }
      ]
    }
  ],
  "xiaomi": [
    {
      "name": "Redmi Note",
      "models": [
        {
          "name": "Redmi Note 14 Pro+ 5G",
          "image": "/images/models/xiaomi/redmi-note-14-pro-plus-5g.webp"
        },
        {
          "name": "Redmi Note 13 Pro+",
          "image": "/images/models/xiaomi/redmi-note-13-pro-plus.webp"
        },
        {
          "name": "Redmi Note 13 Pro 5G",
          "image": "/images/models/xiaomi/redmi-note-13-pro-5g.webp"
        },
        {
          "name": "Redmi Note 13 Pro",
          "image": "/images/models/xiaomi/redmi-note-13-pro.webp"
        },
        {
          "name": "Redmi Note 13",
          "image": "/images/models/xiaomi/redmi-note-13.webp"
        },
        {
          "name": "Redmi Note 12 Pro+",
          "image": "/images/models/xiaomi/redmi-note-12-pro-plus.webp"
        },
        {
          "name": "Redmi Note 12",
          "image": "/images/models/xiaomi/redmi-note-12.webp"
        },
        {
          "name": "Redmi Note 11 Pro+ 5G",
          "image": "/images/models/xiaomi/redmi-note-11-pro-plus-5g.webp"
        },
        {
          "name": "Redmi Note 11 Pro",
          "image": "/images/models/xiaomi/redmi-note-11-pro.webp"
        },
        {
          "name": "Redmi Note 11T 5G",
          "image": "/images/models/xiaomi/redmi-note-11t-5g.webp"
        },
        {
          "name": "Redmi Note 11S",
          "image": "/images/models/xiaomi/redmi-note-11s.webp"
        },
        {
          "name": "Redmi Note 11",
          "image": "/images/models/xiaomi/redmi-note-11.webp"
        },
        {
          "name": "Redmi Note 11 SE",
          "image": "/images/models/xiaomi/redmi-note-11-se.webp"
        },
        {
          "name": "Redmi Note 10 Pro Max",
          "image": "/images/models/xiaomi/redmi-note-10-pro-max.webp"
        },
        {
          "name": "Redmi Note 10 Pro",
          "image": "/images/models/xiaomi/redmi-note-10-pro.webp"
        },
        {
          "name": "Redmi Note 10S",
          "image": "/images/models/xiaomi/redmi-note-10s.webp"
        },
        {
          "name": "Redmi Note 10",
          "image": "/images/models/xiaomi/redmi-note-10.webp"
        },
        {
          "name": "Redmi Note 10 Prime",
          "image": "/images/models/xiaomi/redmi-note-10-prime.webp"
        },
        {
          "name": "Redmi Note 9 Pro Max",
          "image": "/images/models/xiaomi/redmi-note-9-pro-max.webp"
        },
        {
          "name": "Redmi Note 9 Pro",
          "image": "/images/models/xiaomi/redmi-note-9-pro.webp"
        },
        {
          "name": "Redmi Note 9",
          "image": "/images/models/xiaomi/redmi-note-9.webp"
        },
        {
          "name": "Redmi Note 8 Pro",
          "image": "/images/models/xiaomi/redmi-note-8-pro.webp"
        },
        {
          "name": "Redmi Note 8",
          "image": "/images/models/xiaomi/redmi-note-8.webp"
        },
        {
          "name": "Redmi Note (Prime)",
          "image": "/images/models/xiaomi/redmi-note-prime.webp"
        }
      ]
    },
    {
      "name": "Redmi",
      "models": [
        {
          "name": "Redmi 13C",
          "image": "/images/models/xiaomi/redmi-13c.webp"
        },
        {
          "name": "Redmi 13 5G",
          "image": "/images/models/xiaomi/redmi-13-5g.webp"
        },
        {
          "name": "Redmi 12 Pro",
          "image": "/images/models/xiaomi/redmi-12-pro.webp"
        },
        {
          "name": "Redmi 12",
          "image": "/images/models/xiaomi/redmi-12.webp"
        },
        {
          "name": "Redmi 12C",
          "image": "/images/models/xiaomi/redmi-12c.webp"
        },
        {
          "name": "Redmi 11 Prime",
          "image": "/images/models/xiaomi/redmi-11-prime.webp"
        },
        {
          "name": "Redmi 10 Prime",
          "image": "/images/models/xiaomi/redmi-10-prime.webp"
        },
        {
          "name": "Redmi 10X 5G",
          "image": "/images/models/xiaomi/redmi-10x-5g.webp"
        },
        {
          "name": "Redmi 10C",
          "image": "/images/models/xiaomi/redmi-10c.webp"
        },
        {
          "name": "Redmi 10A",
          "image": "/images/models/xiaomi/redmi-10a.webp"
        },
        {
          "name": "Redmi 9 Power",
          "image": "/images/models/xiaomi/redmi-9-power.webp"
        },
        {
          "name": "Redmi 9",
          "image": "/images/models/xiaomi/redmi-9.webp"
        },
        {
          "name": "Redmi 9i",
          "image": "/images/models/xiaomi/redmi-9i.webp"
        },
        {
          "name": "Redmi 9C",
          "image": "/images/models/xiaomi/redmi-9c.webp"
        },
        {
          "name": "Redmi 9A",
          "image": "/images/models/xiaomi/redmi-9a.webp"
        },
        {
          "name": "Redmi 8",
          "image": "/images/models/xiaomi/redmi-8.webp"
        },
        {
          "name": "Redmi 8A",
          "image": "/images/models/xiaomi/redmi-8a.webp"
        },
        {
          "name": "Redmi Y3",
          "image": "/images/models/xiaomi/redmi-y3.webp"
        }
      ]
    },
    {
      "name": "Redmi K",
      "models": [
        {
          "name": "Redmi K80 Pro",
          "image": "/images/models/xiaomi/redmi-k80-pro.webp"
        },
        {
          "name": "Redmi K80",
          "image": "/images/models/xiaomi/redmi-k80.webp"
        },
        {
          "name": "Redmi K40",
          "image": "/images/models/xiaomi/redmi-k40.webp"
        },
        {
          "name": "Redmi K20 Pro",
          "image": "/images/models/xiaomi/redmi-k20-pro.webp"
        },
        {
          "name": "Redmi K20",
          "image": "/images/models/xiaomi/redmi-k20.webp"
        }
      ]
    },
    {
      "name": "POCO",
      "models": [
        {
          "name": "POCO C51",
          "image": "/images/models/xiaomi/poco-c51.webp"
        }
      ]
    },
    {
      "name": "Mi / Xiaomi",
      "models": [
        {
          "name": "Xiaomi 14 Ultra",
          "image": "/images/models/xiaomi/xiaomi-14-ultra.webp"
        },
        {
          "name": "Xiaomi 14 Civi",
          "image": "/images/models/xiaomi/xiaomi-14-civi.webp"
        },
        {
          "name": "Xiaomi 14",
          "image": "/images/models/xiaomi/xiaomi-14.webp"
        },
        {
          "name": "Mi 11 Ultra",
          "image": "/images/models/xiaomi/mi-11-ultra.webp"
        },
        {
          "name": "Mi 11X Pro",
          "image": "/images/models/xiaomi/mi-11x-pro.webp"
        },
        {
          "name": "Mi 11X",
          "image": "/images/models/xiaomi/mi-11x.webp"
        },
        {
          "name": "Mi 11i",
          "image": "/images/models/xiaomi/mi-11i.webp"
        },
        {
          "name": "Mi 11 Lite",
          "image": "/images/models/xiaomi/mi-11-lite.webp"
        },
        {
          "name": "Mi 10T Pro",
          "image": "/images/models/xiaomi/mi-10t-pro.webp"
        },
        {
          "name": "Mi 10T",
          "image": "/images/models/xiaomi/mi-10t.webp"
        },
        {
          "name": "Mi 10i",
          "image": "/images/models/xiaomi/mi-10i.webp"
        },
        {
          "name": "Mi 10",
          "image": "/images/models/xiaomi/mi-10.webp"
        },
        {
          "name": "Black Shark 2",
          "image": "/images/models/xiaomi/black-shark-2.webp"
        }
      ]
    },
    {
      "name": "Other",
      "models": [
        {
          "name": "Other Xiaomi Model",
          "image": "/images/models/xiaomi/other.webp"
        }
      ]
    }
  ],
  "motorola": [
    {
      "name": "Motorola Edge",
      "models": [
        {
          "name": "Edge 60 Pro",
          "image": "/images/models/motorola/edge-60-pro.webp"
        },
        {
          "name": "Edge 60 Fusion",
          "image": "/images/models/motorola/edge-60-fusion.webp"
        },
        {
          "name": "Edge 60 Stylus",
          "image": "/images/models/motorola/edge-60-stylus.webp"
        },
        {
          "name": "Edge 60s",
          "image": "/images/models/motorola/edge-60s.webp"
        },
        {
          "name": "Edge 60",
          "image": "/images/models/motorola/edge-60.webp"
        },
        {
          "name": "Edge 50 Ultra",
          "image": "/images/models/motorola/edge-50-ultra.webp"
        },
        {
          "name": "Edge 50 Pro",
          "image": "/images/models/motorola/edge-50-pro.webp"
        },
        {
          "name": "Edge 50 Fusion",
          "image": "/images/models/motorola/edge-50-fusion.webp"
        },
        {
          "name": "Edge 50 Neo",
          "image": "/images/models/motorola/edge-50-neo.webp"
        },
        {
          "name": "Edge 50",
          "image": "/images/models/motorola/edge-50.webp"
        },
        {
          "name": "Edge 40 Pro",
          "image": "/images/models/motorola/edge-40-pro.webp"
        },
        {
          "name": "Edge 40 Neo",
          "image": "/images/models/motorola/edge-40-neo.webp"
        },
        {
          "name": "Edge 40",
          "image": "/images/models/motorola/edge-40.webp"
        },
        {
          "name": "Edge 30 Ultra",
          "image": "/images/models/motorola/edge-30-ultra.webp"
        },
        {
          "name": "Edge 30 Pro",
          "image": "/images/models/motorola/edge-30-pro.webp"
        },
        {
          "name": "Edge 30 Fusion+",
          "image": "/images/models/motorola/edge-30-fusion-plus.webp"
        },
        {
          "name": "Edge 30 Fusion",
          "image": "/images/models/motorola/edge-30-fusion.webp"
        },
        {
          "name": "Edge 30 Neo",
          "image": "/images/models/motorola/edge-30-neo.webp"
        },
        {
          "name": "Edge 30",
          "image": "/images/models/motorola/edge-30.webp"
        },
        {
          "name": "Edge 20 Pro",
          "image": "/images/models/motorola/edge-20-pro.webp"
        },
        {
          "name": "Edge 20 Fusion",
          "image": "/images/models/motorola/edge-20-fusion.webp"
        },
        {
          "name": "Edge 20 Lite",
          "image": "/images/models/motorola/edge-20-lite.webp"
        },
        {
          "name": "Edge 20",
          "image": "/images/models/motorola/edge-20.webp"
        },
        {
          "name": "Edge (2021)",
          "image": "/images/models/motorola/edge-2021.webp"
        },
        {
          "name": "Edge S30",
          "image": "/images/models/motorola/edge-s30.webp"
        },
        {
          "name": "Edge+",
          "image": "/images/models/motorola/edge-plus.webp"
        },
        {
          "name": "Edge",
          "image": "/images/models/motorola/edge.webp"
        }
      ]
    },
    {
      "name": "Motorola Razr",
      "models": [
        {
          "name": "Razr 60 Ultra",
          "image": "/images/models/motorola/razr-60-ultra.webp"
        },
        {
          "name": "Razr 60",
          "image": "/images/models/motorola/razr-60.webp"
        },
        {
          "name": "Razr+ (2024)",
          "image": "/images/models/motorola/razr-plus-2024.webp"
        },
        {
          "name": "Razr 50 Ultra",
          "image": "/images/models/motorola/razr-50-ultra.webp"
        },
        {
          "name": "Razr 50",
          "image": "/images/models/motorola/razr-50.webp"
        },
        {
          "name": "Razr (2024)",
          "image": "/images/models/motorola/razr-2024.webp"
        },
        {
          "name": "Razr 40 Ultra",
          "image": "/images/models/motorola/razr-40-ultra.webp"
        },
        {
          "name": "Razr 40",
          "image": "/images/models/motorola/razr-40.webp"
        },
        {
          "name": "Razr (2022)",
          "image": "/images/models/motorola/razr-2022.webp"
        },
        {
          "name": "Razr 5G",
          "image": "/images/models/motorola/razr-5g.webp"
        },
        {
          "name": "Razr 2 5G",
          "image": "/images/models/motorola/razr-2-5g.webp"
        },
        {
          "name": "Razr (2019)",
          "image": "/images/models/motorola/razr-2019.webp"
        },
        {
          "name": "Razr (Classic)",
          "image": "/images/models/motorola/razr-classic.webp"
        }
      ]
    },
    {
      "name": "Moto G",
      "models": [
        {
          "name": "Moto G85",
          "image": "/images/models/motorola/moto-g85.webp"
        },
        {
          "name": "Moto G84",
          "image": "/images/models/motorola/moto-g84.webp"
        },
        {
          "name": "Moto G82",
          "image": "/images/models/motorola/moto-g82.webp"
        },
        {
          "name": "Moto G73",
          "image": "/images/models/motorola/moto-g73.webp"
        },
        {
          "name": "Moto G71 5G",
          "image": "/images/models/motorola/moto-g71-5g.webp"
        },
        {
          "name": "Moto G71s",
          "image": "/images/models/motorola/moto-g71s.webp"
        },
        {
          "name": "Moto G64 5G",
          "image": "/images/models/motorola/moto-g64-5g.webp"
        },
        {
          "name": "Moto G62",
          "image": "/images/models/motorola/moto-g62.webp"
        },
        {
          "name": "Moto G60s",
          "image": "/images/models/motorola/moto-g60s.webp"
        },
        {
          "name": "Moto G54",
          "image": "/images/models/motorola/moto-g54.webp"
        },
        {
          "name": "Moto G54 Power",
          "image": "/images/models/motorola/moto-g54-power.webp"
        },
        {
          "name": "Moto G53",
          "image": "/images/models/motorola/moto-g53.webp"
        },
        {
          "name": "Moto G52",
          "image": "/images/models/motorola/moto-g52.webp"
        },
        {
          "name": "Moto G51 5G",
          "image": "/images/models/motorola/moto-g51-5g.webp"
        },
        {
          "name": "Moto G50 5G",
          "image": "/images/models/motorola/moto-g50-5g.webp"
        },
        {
          "name": "Moto G45 5G",
          "image": "/images/models/motorola/moto-g45-5g.webp"
        },
        {
          "name": "Moto G42",
          "image": "/images/models/motorola/moto-g42.webp"
        },
        {
          "name": "Moto G41",
          "image": "/images/models/motorola/moto-g41.webp"
        },
        {
          "name": "Moto G40 Fusion",
          "image": "/images/models/motorola/moto-g40-fusion.webp"
        },
        {
          "name": "Moto G34",
          "image": "/images/models/motorola/moto-g34.webp"
        },
        {
          "name": "Moto G32",
          "image": "/images/models/motorola/moto-g32.webp"
        },
        {
          "name": "Moto G31",
          "image": "/images/models/motorola/moto-g31.webp"
        },
        {
          "name": "Moto G30",
          "image": "/images/models/motorola/moto-g30.webp"
        },
        {
          "name": "Moto G23",
          "image": "/images/models/motorola/moto-g23.webp"
        },
        {
          "name": "Moto G22",
          "image": "/images/models/motorola/moto-g22.webp"
        },
        {
          "name": "Moto G (2022)",
          "image": "/images/models/motorola/moto-g-2022.webp"
        },
        {
          "name": "Moto G200 5G",
          "image": "/images/models/motorola/moto-g200-5g.webp"
        },
        {
          "name": "Moto G100",
          "image": "/images/models/motorola/moto-g100.webp"
        },
        {
          "name": "Moto G14",
          "image": "/images/models/motorola/moto-g14.webp"
        },
        {
          "name": "Moto G13",
          "image": "/images/models/motorola/moto-g13.webp"
        },
        {
          "name": "Moto G9 Plus",
          "image": "/images/models/motorola/moto-g9-plus.webp"
        },
        {
          "name": "Moto G9 Power",
          "image": "/images/models/motorola/moto-g9-power.webp"
        },
        {
          "name": "Moto G9",
          "image": "/images/models/motorola/moto-g9.webp"
        },
        {
          "name": "Moto G9 Play",
          "image": "/images/models/motorola/moto-g9-play.webp"
        },
        {
          "name": "Moto G8 Plus",
          "image": "/images/models/motorola/moto-g8-plus.webp"
        },
        {
          "name": "Moto G8 Power Lite",
          "image": "/images/models/motorola/moto-g8-power-lite.webp"
        },
        {
          "name": "Moto G8 Play",
          "image": "/images/models/motorola/moto-g8-play.webp"
        },
        {
          "name": "Moto G20",
          "image": "/images/models/motorola/moto-g20.webp"
        },
        {
          "name": "Moto G 5G Plus",
          "image": "/images/models/motorola/moto-g-5g-plus.webp"
        },
        {
          "name": "Moto G 5G",
          "image": "/images/models/motorola/moto-g-5g.webp"
        },
        {
          "name": "Moto G Stylus 5G",
          "image": "/images/models/motorola/moto-g-stylus-5g.webp"
        },
        {
          "name": "Moto G Power (2021)",
          "image": "/images/models/motorola/moto-g-power-2021.webp"
        },
        {
          "name": "Moto G Pure",
          "image": "/images/models/motorola/moto-g-pure.webp"
        },
        {
          "name": "Moto G7 Plus",
          "image": "/images/models/motorola/moto-g7-plus.webp"
        },
        {
          "name": "Moto G7 Play",
          "image": "/images/models/motorola/moto-g7-play.webp"
        },
        {
          "name": "Moto G04",
          "image": "/images/models/motorola/moto-g04.webp"
        },
        {
          "name": "Moto G10 Power",
          "image": "/images/models/motorola/moto-g10-power.webp"
        }
      ]
    },
    {
      "name": "Moto E",
      "models": [
        {
          "name": "Moto E32s",
          "image": "/images/models/motorola/moto-e32s.webp"
        },
        {
          "name": "Moto E32",
          "image": "/images/models/motorola/moto-e32.webp"
        },
        {
          "name": "Moto E30",
          "image": "/images/models/motorola/moto-e30.webp"
        },
        {
          "name": "Moto E20",
          "image": "/images/models/motorola/moto-e20.webp"
        }
      ]
    },
    {
      "name": "Moto One",
      "models": [
        {
          "name": "One 5G",
          "image": "/images/models/motorola/one-5g.webp"
        },
        {
          "name": "One Hyper",
          "image": "/images/models/motorola/one-hyper.webp"
        },
        {
          "name": "One Fusion+",
          "image": "/images/models/motorola/one-fusion-plus.webp"
        },
        {
          "name": "One Fusion",
          "image": "/images/models/motorola/one-fusion.webp"
        },
        {
          "name": "One Action",
          "image": "/images/models/motorola/one-action.webp"
        },
        {
          "name": "One Zoom",
          "image": "/images/models/motorola/one-zoom.webp"
        },
        {
          "name": "One Macro",
          "image": "/images/models/motorola/one-macro.webp"
        },
        {
          "name": "One Vision",
          "image": "/images/models/motorola/one-vision.webp"
        },
        {
          "name": "One Power (P30 Note)",
          "image": "/images/models/motorola/one-power-p30-note.webp"
        },
        {
          "name": "One P30 Play",
          "image": "/images/models/motorola/one-p30-play.webp"
        }
      ]
    },
    {
      "name": "Moto Z & Legacy",
      "models": [
        {
          "name": "Moto X30 Pro",
          "image": "/images/models/motorola/moto-x30-pro.webp"
        },
        {
          "name": "Moto X30",
          "image": "/images/models/motorola/moto-x30.webp"
        },
        {
          "name": "Moto Z4",
          "image": "/images/models/motorola/moto-z4.webp"
        },
        {
          "name": "Moto Z4 Force",
          "image": "/images/models/motorola/moto-z4-force.webp"
        },
        {
          "name": "Moto Z3",
          "image": "/images/models/motorola/moto-z3.webp"
        },
        {
          "name": "Moto Z3 Play",
          "image": "/images/models/motorola/moto-z3-play.webp"
        },
        {
          "name": "Moto Z2 Force",
          "image": "/images/models/motorola/moto-z2-force.webp"
        },
        {
          "name": "Moto P30",
          "image": "/images/models/motorola/moto-p30.webp"
        }
      ]
    }
  ]
};
